version: '2'
services:
  db:
    container_name: todo-list-db
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  php:
    container_name: todo-list-api
    build: ./php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ./api:/var/www/api:cached
      - ./logs/api:/var/www/api/var/log:cached
    depends_on:
      - db
  nginx:
    container_name: todo-list-nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./api:/var/www/api:cached
  ui:
    container_name: todo-list-ui
    build: ./ui
    ports:
      - "3000:3000"
    command: "npm run start"
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    environment:
      - REACT_APP_PORT=3000
      - REACT_APP_SERVER_URL=http://localhost:9000/
volumes:
  mysql-data: {}
