fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: force
  view:
    view_response_listener: 'force'
    formats:
      json: true
sensio_framework_extra:
  request: { converters: true }
  view: { annotations: true }
